# Generated by Django 3.2.7 on 2021-11-15 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(default=datetime.date(2021, 11, 15), null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
