# Generated by Django 3.2.7 on 2021-10-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_alter_course_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
